//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class angulartetris_highscores
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int Score { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
